version: '3.8'

services:
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "80:80" # Changed from "3005:3000" to "80:80" assuming Nginx is now configured to listen on 80
    volumes:
      - ./my-app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Ensure this matches what your Nginx proxy_pass is configured to if using Nginx to proxy requests to the backend
