version: '3.8'

services:
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3005:3000"
    volumes:
      - ./my-app/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
